services:
  tor:
    container_name: tor
    image: dockurr/tor:latest
    ports:
      - 9050:9050
      - 9051:9051
    volumes:
      - /path/to/config:/etc/tor
      - /path/to/data:/var/lib/tor
    stop_grace_period: 1m
